### ISSUE TITLE
ライブラリの置き換えが多重に定義された場合にデッドロックになる

### ISSUE THREAD

**Issue by asmka** [noradium/dac#19]
## 現象
本拡張機能と同様のfetchThreadライブラリ関数の置き換え処理を別の拡張機能でも定義された場合，動画ページの読み込みが停止

## 原因
getWatchAppJsURI関数では"watch_app_\*.js"にマッチする __最初__ のURLを返す．
https://github.com/noradium/dac/blob/1d3eba6d8686ad08fa81e43a49cd5cb134c03e88/src/scripts/index.js#L107-L109

その取得したURL中のwebRequestは停止し，後ろに"?by-{_extension name_}"付加した新URLを埋め込むことで，置き換え後のfetchThreadが"watch_app_\*?by-{_extension name_}.js"から呼び出されるようにしている．
https://github.com/noradium/dac/blob/1d3eba6d8686ad08fa81e43a49cd5cb134c03e88/src/scripts/background.js#L7-L9
https://github.com/noradium/dac/blob/1d3eba6d8686ad08fa81e43a49cd5cb134c03e88/src/scripts/index.js#L11-L12

同等の処理を別の拡張機能でも実施した場合，以下2つのURLが埋め込まれる．
- "watch_app_\*?by-danime-another-comment.js"
- "watch_app_\*?by-{別の拡張機能名}.js"

別の拡張機能の効果で"watch_app_\*?by-danime-another-comment.js"中のwebRequest停止，本拡張機能の効果で"watch_app_\*?by-{別の拡張機能名}"中のwebRequest停止が発生し，webRequestがデッドロックしてしまうため．

## 対処
getWatchAppJsURI関数で"watch_app_\*.js"にマッチする __最後__ のURLを返すよう修正
```
-  })[0];
+  }).pop();
```
- ロード順が本拡張機能，別の拡張機能の場合
1. 本拡張機能で"watch_app_\*?by-danime-another-comment.js"の埋め込み
2. 別の拡張機能で"watch_app_\*?by-danime-another-comment.js&by-{別の拡張機能名}"の埋め込み
- ロード順が別の拡張機能，本拡張機能の場合
1. 別の拡張機能で"watch_app_\*?by-{別の拡張機能名}"の埋め込み
2. 本拡張機能で"watch_app_\*?by-{別の拡張機能名}&by-danime-another-comment.js"の埋め込み

最終的に両方の拡張機能名が入ったURLが埋め込まれるので，そのURL内ではwebRequestは停止されない

## 確認
そもそも別の拡張機能で同処理を実施する想定があるか確認したいです．
一応新規URLに"&by-*"を埋め込むパターンもあったので，想定しているのかと推測しました．
想定しておらず対処不要であればCloseします．

## 備考
本ソースを参考にfetchThread処理の書き換え処理を含む拡張機能を作成していたところ，本事象を確認しました．
本対処がなくても，別の拡張機能側でのみ本対処を実施し，setTimeout等で別の拡張機能のinjectの方が後になるよう調整すれば回避できます．

**Comment by noradium** [comment]
@dff9th 
なるほど
このパターンは想定してませんでした。
> 新規URLに"&by-*"を埋め込むパターンもあったので

これは単純にもともとのURLにクエリが付いていてもいいようにという理由ですね。

別の拡張機能で同様の処理をやりたいとのことで、ある拡張の中から他の拡張の存在を気にしないといけないのは微妙なので、対応すべきかなと思います
プルリクの方も問題なさそうなのでマージしてしまおうと思いますがよさそうですか？

**Comment by asmka** [comment]
@noradium 
> これは単純にもともとのURLにクエリが付いていてもいいようにという理由ですね。

なるほど承知しました．

> プルリクの方も問題なさそうなのでマージしてしまおうと思いますがよさそうですか？

はい，問題ないようであればマージしていただけると幸いです．
ありがとうございます．

**Comment by noradium** [comment]
ストアの方も更新しましたが審査が必要になっていたので少し時間がかかるかもです
プルリクありがとうございました！

**Comment by asmka** [comment]
v1.5.1版で本事象が起きないことを確認しました！
対応ありがとうございました！
